### ISSUE TITLE
termux-job-scheduler always defaulting to 900000 milliseconds

### ISSUE THREAD

**Issue by heywoodlh** [termux/termux-api-package#77]
when trying to schedule a job to run every 300000 milliseconds using the `--period-ms` flag, it always goes to 900000 milliseconds. 

```
$ termux-job-scheduler --period-ms 300000 --script /data/data/com.termux/files/home/scripts/check-shell.sh --network any

Scheduling Job 0: /data/data/com.termux/files/home/scripts/check-shell.sh       (periodic: 900000ms) (battery not low) (network: NetworkRequest [ NONE id=0, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&VALIDATED Unwanted:  Uid: 10121] ]) - response 1
```

What am I doing wrong? Or is this a known issue?

**Comment by xalexalex** [comment]
Since Android N there's a minimum period below which you can't go ([`JobInfo.getMinPeriodMillis()`](https://developer.android.com/reference/kotlin/android/app/job/JobInfo.html#getMinPeriodMillis())) and it is 900.000 ms (15 minutes).

I just added it to the documentation and it will be available in the next version of the termux-api package.

Thanks for pointing this out!

**Comment by heywoodlh** [comment]
Thanks for the quick response @xalexalex :)

**Comment by xalexalex** [comment]
Gotta make these August Sundays useful somehow! Glad I could help :smile:
